spring:
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:orcl
        username: utc_java
        password: 123456
    jpa:
        hibernate:
            ddl-auto: none
        database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

utc:
    java:
        jwtToken: utcJava
        jwtSecret: a21ZQ7Nf0Ek2ZvtOn0UeZDYqN8WfNtO29cfXwV5gy4I=
        jwtExpirationMs: 86400000
        tokenPrefix: utcJava_

server:
    port: 8080