spring:
    datasource:
#        url: jdbc:oracle:thin:@localhost:1521:orcl
#        username: utc_java
#        password: 123456
        url: jdbc:mysql://localhost:3310/utc_java
        username: unittest
        password: unittest
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
#                ddl-auto: none
#            database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

utc:
    java:
        jwtToken: utcJava
        jwtSecret: a21ZQ7Nf0Ek2ZvtOn0UeZDYqN8WfNtO29cfXwV5gy4I=
        jwtExpirationMs: 86400000
        tokenPrefix: utcJava_

server:
    port: 8080