@startuml
start
if (Nếu quyền user thực thi api không phải ADMIN) is (yes) then
  :trả ra mã lỗi 403 không có quyền tạo mới;
  stop
endif
: kiểm tra dữ liệu đầu vào với \n - title: không được để trống, giới hạn 128 ký tự \n - content: không được để trống , giới hạn 10000 ký tự ;
   if (kiểm tra lỗi) is (yes) then
     : trả ra lỗi 400 tham số truyền vào không hợp lệ;
     stop
   endif
 : truy vấn thông tin user tạo news với username \n đăng nhập lấy từ SecurityContextHolder;
  if (Nếu không có thông tin trong database) is (yes) then
    :trả ra lỗi 404 không tìm thấy user;
  stop
  endif
  : tạo mới bản tin với thông tin truyền vào tương ứng;
 : lưu thông tin bản tin mới vào database \n và trả ra mã lỗi 200 SUCCESS;
stop
@enduml